[book]
title = "QAIL Documentation"
authors = ["QAIL Team"]
language = "en"

[build]
build-dir = "../../qail-web/public/docs"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/qail-io/qail"
edit-url-template = "https://github.com/qail-io/qail/edit/main/docs/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["theme/header.js"]
